[package]
name = "sanca"
version = "1.1.0"
edition = "2021"
description = "A scanner to discover what technologies are running on a remote host. Focus on providing evidences."
readme = "README.md"
repository = "https://github.com/nalysius/sanca"
keywords = ["scanner", "cybersecurity"]
categories = ["command-line-utilities"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
clap = { version = "4.4.11", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["gzip"] }
tokio = "1.34.0"
futures = "0.3.29"
log = "0.4.20"
simple_logger = "4.3.0"